name: LoVTP
version: '${project.version}'
main: net.nutchi.lovtp.LoVTP
api-version: '1.19'
commands:
  lovtp:
    permission: lovtp.command.lovtp
  lovtpreload:
    permissions: lovtp.command.reload
  lovtpsetspawn:
    permission: lovtp.command.setspawn
permissions:
    lovtp.command.lovtp:
      default: op
    lovtp.command.reload:
      default: op
    lovtp.command.setspawn:
      default: op
